spring:
  application:
    name: cgsc
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: viratech
    password: root

  jpa:
    properties:
      hibernate:
        default_schema: cgsc
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    schemas: ${spring.jpa.properties.hibernate.default_schema}
    baseline-on-migrate: true
    locations:
      - "classpath:migrations"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

github:
  url: https://api.github.com

server:
  port: 8086

